### ISSUE TITLE
Feature request: implement Filters

### ISSUE THREAD

**Issue by emdalton** [PoetOS/moodle-local_metadata#5]
Moodle Filters allow data to be included in text fields using tokens: https://docs.moodle.org/33/en/Filters

It would be helpful to implement metadata fields as filters. Then the values could be reflected in Labels, HTML blocks, Activity descriptions, etc. This would make the metadata fields much more generally useful.

**Comment by mchurchward** [comment]
Adding your comment from the plugins directory:

> [T]he idea would be to create filters, e.g. [course:subject] to include the data from a field named "subject" attached to the context "course".

Okay. I could see this as being valuable for sure. I guess this would need to be a "companion" filter plugin. I'm guessing we would need to agree on a format to display the placeholders like you mentioned in your comment, but clearly identifies as metadata. Maybe:
[[metadata::_context_::_dataname_]]

So, you would enter something like:

  This course awards [[metadata::course::credits]] credits to your program on completion.

And it would display:
  This course awards 3 credits to your program on completion.

If the "credits" metadata item existed with the course context item the text was attached to, and its value was "3".

I wonder if we also need to allow for a specific context instance value to be added so that the values could be displayed in text not attached to a context being requested? (thinking...)

**Comment by emdalton** [comment]
Sure, Drupal allows this with a similar feature. It would look something like
[[metadata::course=12345::credits]] or possibly [[metadata::courseid=12345::credits]]

**Comment by mchurchward** [comment]
Created https://github.com/PoetOS/moodle-filter_metadata to begin work on the filter.

**Comment by mchurchward** [comment]
Hi. I have committed a working Beta version of the metadata filter to https://github.com/PoetOS/moodle-filter_metadata. It works, but needs some work to assure permissions to the data. The format is:
{{metadata::_context_=_instanceid_::_fieldshortname_}}
The "=instanceid" is optional. If not specified, the filter will attempt to determine if there is a valid instance id from the context of the page being viewed. For example, a course id on a course page, or a module id on an activity page.
I'm going to close this issue. Please add any comments on the filter to the filter repository page.
